name: CI

on:
  pull_request:
    branches:
      - work
  push:
    branches:
      - work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Test
        run: npm run test -- --run

      - name: Check roadmap gate
        run: npm run check:roadmap

      - name: Validate guards
        if: github.event_name == 'pull_request'
        env:
          GUARD_BASE_REF: ${{ github.event.pull_request.base.sha }}
        run: npm run validate-guards
